# Generated by Django 4.0.3 on 2025-04-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210320_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Uniform', 'Uniform')], max_length=50, null=True),
        ),
    ]
